# Generated by Django 4.2.10 on 2024-03-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdesc', models.CharField(max_length=255)),
                ('cimage', models.ImageField(upload_to='courseimage')),
            ],
        ),
    ]
